In [6]:
#%run kn1d_test.py
####
## For python 3.12.4 is not running
##
####
## For fixed the updates on the routines, a test with input files is performed
##
## --> Version on this ipynb is 3.12.4

In [9]:
from KN1D import KN1D
import scipy.io as sio
from scipy.io import readsav
import numpy as np
print('test','\n')
import matplotlib.pyplot as plt
from scipy import interpolate
import time

#fileloc="C:\\Users\\nholl\\OneDrive\\Documents\\School Work\\Research Info\\ADAS Outputs\\"

testidl=True

def read_sav(file_name):

# This function will print the data from an IDL .sav file
# Inputs:
#   file name - the name of the .sav file
# Outputs:
#   sav_data - a dictionary containing all of the data
    path = file_name
    sav_data = readsav(path)
    return sav_data

fname='1090904024_950to1050'
fname2='test_qcx_h0'
#fname2='No_collisions'

test 



In [10]:
data_file = read_sav(fname+'.sav')

keys = data_file.keys() # gets the keys from the dictionary  
keys_list = list(keys)  # puts the keys into a list 
#print(keys_list)
#print(keys_list[0])

values = data_file.values() # gets the values from the dictionary 
values_list = list(values)  # puts the values into a list 
#print(values_list)
#print('x', values_list[3])
#print('xlim', values_list[4])
#print('xsept', values_list[5])
#print('GuageH2', 50)
#print('mu', values_list[7])
#print('vx', values_list[11])
#print('LC', values_list[12])
#print('PipeDia', values_list[13])
#print(keys_list[3])
#raise Exception('check')
for i in keys_list:
    #print(i,data_file[i])
        pass

#interpfunc=interpolate.interp1d(data_file['x'],data_file['n_e'])
#x=np.linspace(data_file['x'][0],data_file['x'][-1],1000)

#plt.plot(x,interpfunc(x))
#plt.xlabel(r'Distance (m)')
#plt.ylabel(r'Density (m$^{-3}$)')

#plt.show()
# x  = values_list[3] # this calls the x np.array from the list of values 
# print(x)
# KN1D(x, xlimiter, xsep, GaugeH2, mu, Ti, Te, n, vxi, LC, PipeDia, \
#         truncate = 1.0e-3, refine = 0, File = '', NewFile = 0, ReadInput = 0, \
#         error = 0, compute_errors = 0, plot = 0, debug = 0, debreif = 0, pause = 0, \
#         Hplot = 0, Hdebug = 0, Hdebreif = 0, Hpause = 0, \
#         H2plot = 0, H2debug = 0, H2debreif = 0, H2pause = 0)
#print(data_file['nH2'])
for i in ['x','x_lim','x_sep','guageH2','mu','t_i','t_e','n_e','vx','lc','d_pipe']:
    #print(i,':',data_file.get(i,50))
    pass

In [11]:
xH2, nH2, GammaxH2, TH2, qxH2_total, nHP, THP, SH, SP, \
                xH, nH, GammaxH, TH, qxH_total, NetHSource, \
                    Sion, QH_total, SideWallH, Lyman, Balmer=\
                KN1D( data_file['x'], data_file['x_lim'], data_file['x_sep'], \
                     data_file['p_wall'], data_file['mu'], data_file['t_i'], \
                        data_file['t_e'], data_file['n_e'], data_file['vx'], \
                            data_file['lc'], data_file['d_pipe'])

ValueError: operands could not be broadcast together with shapes (20,) (6,) 

In [14]:
#def KN1D(x, xlimiter, xsep, \
#         GaugeH2, mu, Ti, \ --->  GaugeH2 == p_wall
#         Te, n, vxi, \
#         LC, PipeDia, truncate = 1.0e-3, \
#         refine = 0, File = '', NewFile = 0, \
#         ReadInput = 0, error = 0, compute_errors = 0, \
#         plot = 0, debug = 0, debrief = 0, \
#         pause = 0, Hplot = 0, Hdebug = 0, \
#         Hdebrief = 0, Hpause = 0, H2plot = 0, \
#         H2debug = 0, H2debrief = 0, H2pause = 0, \
#         adas_rec_h1s=None, adas_ion_h0=None, adas_qcx_h0=None):  # deleted what i added before dont know what I was thinking?? - GG 2/19, corrected typos


In [15]:
####
## Libraries for KN1D
##
import numpy as np 
import os
from scipy import interpolate

from read import sav_read, nc_read
from edit_keys import edit_keys
from create_kinetic_h2_mesh import create_kinetic_h2_mesh
from create_shifted_maxwellian import create_shifted_maxwellian # fixed function name - nh
from integ_bl import integ_bl
from Make_dVr_dVx import Make_dVr_dVx
from sval import sval
from interp_fvrvxx import interp_fvrvxx
from create_kinetic_h_mesh import create_kinetic_h_mesh
from kinetic_h import kinetic_h 
from kinetic_h2 import Kinetic_H2 
from interp_scalarx import interp_scalarx 
from lyman_alpha import Lyman_Alpha
from balmer_alpha import Balmer_Alpha 

from global_vars import mH, q, k_boltz, Twall
from global_vars import global_vars

import copy

In [16]:
####
## inputs from files .sav
##
#data_file['x'], data_file['x_lim'], data_file['x_sep'], \
#                     data_file['p_wall'], data_file['mu'], data_file['t_i'], \
#                        data_file['t_e'], data_file['n_e'], data_file['vx'], \
#                            data_file['lc'], data_file['d_pipe']
##
x = copy.copy(data_file['x']) 
xlimiter = copy.copy(data_file['x_lim']) 
xsep = copy.copy(data_file['x_sep'])
GaugeH2 = copy.copy(data_file['p_wall']) 
mu = copy.copy(data_file['mu']) 
Ti = copy.copy(data_file['t_i']) 
Te = copy.copy(data_file['t_e']) 
n = copy.copy(data_file['n_e']) 
vxi = copy.copy(data_file['vx']) 
LC = copy.copy(data_file['lc']) 
PipeDia = copy.copy(data_file['d_pipe'])

In [17]:
####
## By default 
##  
truncate = 1.0e-3
refine = 0 
File = '' 
NewFile = 0
ReadInput = 0 
error = 0 
compute_errors = 0
plot = 0 
debug = 0 
debrief = 0
pause = 0 
Hplot = 0 
Hdebug = 0
Hdebrief = 0 
Hpause = 0 
H2plot = 0
H2debug = 0 
H2debrief = 0 
H2pause = 0
adas_rec_h1s=None 
adas_ion_h0=None 
adas_qcx_h0=None

In [18]:
g = global_vars() # moved global_vars decleration up

In [19]:
# KN1D_Collisions common block - GG 2/15
H2_H2_EL = g.KN1D_Collisions_H2_H2_EL # fixed typo - GG 2/19
H2_P_EL = g.KN1D_Collisions_H2_P_EL
H2_H_EL = g.KN1D_Collisions_H2_H_EL
H2_HP_CX = g.KN1D_Collisions_H2_HP_CX
H_H_EL = g.KN1D_Collisions_H_H_EL
H_P_EL = g.KN1D_Collisions_H_P_EL
H_P_CX = g.KN1D_Collisions_H_P_CX
Simple_CX = g.KN1D_Collisions_Simple_CX

In [20]:
prompt = 'KN1D => '

In [21]:
#   KN1D_internal common block - GG 2/15
fH_s = g.KN1D_internal_fH_s
fH2_s = g.KN1D_internal_fH2_s
nH2_s = g.KN1D_internal_nH2_s
SpH2_s = g.KN1D_internal_SpH2_s
nHP_s = g.KN1D_internal_nHP_s
THP_s = g.KN1D_internal_THP_s

In [22]:
# Set defaults - GG - 2/15
interp_debug = 0 
max_gen = 100
error = 1 # This i think should be moved to the keyword in the call line

In [23]:
# Option: Read input parameters stored in file from previous run
if ReadInput: 
    input = File
    fp = os.path.exists(input)
    if fp:
        if debrief:
            print(prompt, ' Reading input variables stored in ', input)
            if File[ len(File) - 4 : len(File) ] == '.sav':
                input_dict = sav_read(File, '//Users/Gwen/Desktop/test.nc')
            elif File[ len(File) - 3 : len(File)]=='.nc': # fixed typo
                input_dict = nc_read(File)
            else: 
                if debug:
                    print(prompt, ' Error reading the file') # may be missing some statements 
                    print(prompt, ' finished')
                    # Press_return
#                    return 
    else:
        try:
            input_dict=sav_read(File+'.KN1D_input',File+'_asnetcdf.nc') # allows for old-style inputs, might be removed later - nh
        except:
            print(prompt, 'Error reading the file')
            if debug:
                print(prompt, ' Finished ')
#                return 
    # edit keys for C-Mod Files 
    edit_keys(input_dict) # Not sure if we need this in the final code - not sure the C-Mod files are really intended to be used as inputs - nh
    
    #for i in ['xH2','TiM','TeM','nM','PipeDiaM','vxM','vrM','TnormM','xH','TiA','TeA','nA','PipeDiaA','vxA','vrA','TnormA']:
    #    globals()[i]=input_dict[i.lower()] # Takes entries from input_dict and defines them as variables 
        #   slightly messy, but should solve comment below - nh
    # i think in the end we will have to use the dictionary to manually define the variables
else:
    # determine optimized vr, vx, grid for kinetc_h2 (molecules, M)
    nv = 6
    Eneut = np.array([0.003,0.01,0.03,0.1,0.3,1.0,3.0])
    fctr = 0.3
    if GaugeH2 > 15.0:
        fctr = fctr * 15 / GaugeH2
    xH2,TiM,TeM,nM,PipeDiaM,vxM,vrM,TnormM = create_kinetic_h2_mesh(nv, mu, x, Ti, Te, n, PipeDia, E0 = Eneut, ixE0 = 0 ,irE0 = 0,fctr = fctr) # replaced function inputs, split output list into variables - nh // fixed keyword inputs - GG
    
    # determine optimized vr, vx grid for kinetic_h (atoms, A)
    nv = 10
    fctr = 0.3
    if GaugeH2 > 30.0 :
        fctr = fctr * 30 / GaugeH2
    xH,TiA,TeA,nA,PipeDiaA,vxA,vrA,TnormA= create_kinetic_h_mesh(nv,mu,x,Ti,Te,n,PipeDia, E0 = 0, ixE0 = 0 ,irE0 = 0,fctr = fctr, g=g) # finished line since create_kinetic_h_mesh has been programmed - nh // fixed capitalization - GG // fixed keyword inputs - GG
    
if mu==1:
    _p='H!U+!N'
    _H='H!U0!N'
    _H1s='H(1s)'
    _Hs='H!U*!N(2s)'
    _Hp='H!U*!N(2p)'
    _Hn2='H!U*!N(n=2)'
    _Hn3='H!U*!N(n=3)'
    _Hn='H!U*!N(n>=2)'
    _HH='H!D2!N'
    _Hp='H!D2!U+!N'
else:
    _p='D!U+!N'
    _H='D!U0!N'
    _H1s='D(1s)'
    _Hs='D!U*!N(2s)'
    _Hp='D!U*!N(2p)'
    _Hn2='D!U*!N(n=2)'
    _Hn3='D!U*!N(n=3)'
    _Hn='D!U*!N(n>=2)'
    _HH='D!D2!N'
    _Hp='D!D2!U+!N'

plus=' + '
arrow=' -> '
elastic=' (elastic)'
_e='e!U-!N'
_hv='hv'

v0_bar=np.sqrt(8.0*Twall*q/(np.pi*2*mu*mH))

In [24]:
#   Set up molecular flux BC from inputted neutral pressure

ipM=(vxM>0).nonzero()[0]
inM=(vxM<0).nonzero()[0]
nvrM=vrM.size
nvxM=vxM.size
nxH2=xH2.size
        
#   Code below uses variables defined in create_kinetic_h_mesh
        
ipA=(vxA>0).nonzero()[0]
inA=(vxA<0).nonzero()[0]
nvrA=vrA.size
nvxA=vxA.size
nxH=xH.size

In [28]:
nvrA

20

In [29]:
nvxA

40

In [30]:
nxH

145

In [31]:
#  Code blocks below use common block variables, should be filled in later
#  Initialize fH and fH2 (these may be over-written by data from and old run below)
        
if refine: # sets values to previously computed values, maybe we wont do this at least not necessary now - GG
    if fH_s == None: # updated it via common block - GG 2/15
        fH = np.zeros((nvrA,nvxA,nxH)).T
    else:
        fH = fH_s
    if fH2_s == None: 
        fH2 = np.zeros((nvrM,nvxM,nxH2)).T
    else:
        fH2 = fH2_s
    if nH2_s == None:
        nH2 = np.zeros(nxH2)
    else:
        nH2 = nH2_s
    if nHP_s == None:
        nHP = np.zeros(nxH2)
    else:
        nHP = nHP_s
    if THP_s == None:
        THP = np.zeros(nxH2)
    else:
        THP = THP_s
else:
    fH = np.zeros((nvrA,nvxA,nxH)).T
    fH2 = np.zeros((nvrM,nvxM,nxH2)).T
    nH2 = np.zeros(nxH2)
    nHP = np.zeros(nxH2)
    THP = np.zeros(nxH2)
         
#   Convert pressure (mtorr) to molecular density and flux

fh2BC=np.zeros((nvxM,nvrM)) # fixed mistake in defining the array - GG
DensM=3.537e19*GaugeH2
GammaxH2BC=0.25*DensM*v0_bar
Tmaxwell=np.full(nvxM, Twall) # changed list to numpy array 
vx_shift=np.zeros(nvxM) # fixed size of arrays, its unclear in the original code if this is whats supposed to be done but the for loop in create shifted_maxwellian_include wont owrk otherwise - G
mol=2
Maxwell=create_shifted_maxwellian(vrM,vxM,Tmaxwell,vx_shift,mu,mol,TnormM)
fh2BC[ipM]=Maxwell[0,ipM] # fixed indexing - GG

# Compute NuLoss:
    # NuLoss = Cs/LC
Cs_LC=np.zeros(LC.size)
for ii in range(LC.size):
    if LC[ii]>0:
        Cs_LC[ii]=np.sqrt(q*(Ti[ii]+Te[ii])/(mu*mH))/LC[ii] # fixed notation of indexing arrays - GG
interpfunc = interpolate.interp1d(x,Cs_LC) # fixed the way interpolation was called - GG
NuLoss = interpfunc(xH2)

In [32]:
#  Compute first guess SpH2

#   If plasma recycling accounts for molecular source, then SpH2 = 1/2 n Cs/LC (1/2 accounts for H2 versus H)
#   But, allow for SpH2 to be proportional to this function:
#      SpH2 = beta n Cs/LC 
#   with beta being an adjustable parameter, set by achieving a net H flux of zero onto the wall.
#   For first guess of beta, set the total molecular source according to the formula
        
# (See notes "Procedure to adjust the normalization of the molecular source at the 
#   limiters (SpH2) to attain a net zero atom/molecule flux from wall")
        
#	Integral{SpH2}dx =  (2/3) GammaxH2BC = beta Integral{n Cs/LC}dx
        
nCs_LC=n*Cs_LC

interpfunc = interpolate.interp1d(x,nCs_LC,fill_value="extrapolate",bounds_error=False) # fixed the way interpolation was called - GG
SpH2_hat=interpfunc(xH2)

SpH2_hat=SpH2_hat/integ_bl(xH2,SpH2_hat,value_only=1) # not sure if this line is correct
beta=2/3*GammaxH2BC
if refine: # readded this section now that we have the internal common block called - GG 2/15
    if SpH2_s!=None:
        SpH2=SpH2_s # from kn1d_internal common block
    else:
        SpH2=beta*SpH2_hat
else:
    SpH2=beta*SpH2_hat
SH2=copy.deepcopy(SpH2)

#   Interpolate for vxiM and vxiA

interpfunc = interpolate.interp1d(x,vxi,fill_value="extrapolate")
vxiM = interpfunc(xH2)

interpfunc = interpolate.interp1d(x,vxi,fill_value="extrapolate")
vxiA = interpfunc(xH)

iter=0
EH_hist=np.array([0.0])
SI_hist=np.array([0.0])
oldrun=0

In [33]:
#   Option: Read results from previous run

    #   Will do later after discussing save/restore

#   Starting back at line 378 from IDL code
#   Test for v0_bar consistency in the numerics by computing it from a half maxwellian at the wall temperature

vthM=np.sqrt(2*q*TnormM/(mu*mH))
Vr2pidVrM,VrVr4pidVrM,dVxM=Make_dVr_dVx(vrM,vxM)[0:3]
vthA=np.sqrt(2*q*TnormA/(mu*mH))
Vr2pidVrA,VrVr4pidVrA,dVxA=Make_dVr_dVx(vrA,vxA)[0:3]

nbarHMax=np.sum(Vr2pidVrM*np.matmul(dVxM,fh2BC))
vbarM=2*vthM*np.sum(Vr2pidVrM*np.matmul(vxM*dVxM,fh2BC))/nbarHMax
vbarM_error=abs(vbarM-v0_bar)/max(vbarM,v0_bar)

nvrM=vrM.size
nvxM=vxM.size
vr2vx2_ran2=np.zeros((nvrM,nvxM)).T # fixed indexing - GG

mwell=Maxwell[0,:,:] #  variable named 'Max' in original code; changed here to avoid sharing name with built in function

nbarMax=np.sum(Vr2pidVrM*np.matmul(dVxM,mwell))
UxMax=vthM*np.sum(Vr2pidVrM*np.matmul(vxM*dVxM,mwell))/nbarMax
for i in range(nvrM):
    vr2vx2_ran2[:,i]=vrM[i]**2+(vxM-UxMax/vthM)**2
TMax=2*mu*mH*vthM**2*np.sum(Vr2pidVrM*np.matmul(dVxM,vr2vx2_ran2*mwell))/(3*q*nbarMax)

UxHMax=vthM*np.sum(Vr2pidVrM*np.matmul(vxM*dVxM,fh2BC))/nbarHMax
for i in range(nvrM):
    vr2vx2_ran2[:,i]=vrM[i]**2+(vxM-UxHMax/vthM)**2
THMax=(2*mu*mH)*vthM**2*np.sum(Vr2pidVrM*np.matmul(dVxM,vr2vx2_ran2*fh2BC))/(3*q*nbarHMax)

if compute_errors and debrief:
    print(prompt+'VbarM_error: '+sval(vbarM_error))
    print(prompt+'TWall Maxwellian: '+sval(TMax))
    print(prompt+'TWall Half Maxwellian: '+sval(THMax))

In [34]:
#   Option to view inputted profiles

    #   Plotting - will maybe add later

#   Starting back at line 429 from IDL code
            
if oldrun:
    # checks if the previous run satisfies the required conditions 
    if debrief: 
        print(prompt, 'Maximum Normalized change in nH2: ', sval(nDelta_nH2))
#    if debrief and pause: 
        # press_return 
#        return
    if nDelta_nH2 > truncate: # --> verifies after a first run in the original code
        # goto fH_fH2_iterate I think we will have to make fH_fH2_iterate a function 
        # since we wont be reading old runs right now I am going to leave this as is 
        pass
else:
    #   Entry point for fH_fH2 iteration : iterates through solving fh and fh2 until they satisfy boltzmans equation
    nDelta_nH2 = truncate + 1
    ##while nDelta_nH2 > truncate: # Used goto statements in IDL; changed here to while loop
    ##    if debrief: 
    ##        print(prompt, 'Maximum Normalized change in nH2: ', sval(nDelta_nH2))
    ##    if debrief and pause: 
            # press_return
    ##        pass

        # iter+=1 I dont think this line is necessary 
    ##    if debrief:
    ##        print(prompt+'fH/fH2 Iteration: '+sval(iter))
    ##    nH2s = copy.deepcopy(nH2)

In [35]:
# interpolate fH data onto H2 mesh: fH -> fHM
do_warn=5e-3
fHM=np.maximum(interp_fvrvxx(fH,vrA,vxA,xH,TnormA,vrM,vxM,xH2,TnormM,do_warn=do_warn, debug=interp_debug, g=g) ,0)

# Compute fH2 using Kinetic_H2
ni_correct=1
Compute_H_Source=1
H2compute_errors=compute_errors and H2debrief # is this accurate, how can it be equal to both? - GG 2/15
fH2, nHP, THP, nH2, GammaxH2, VxH2, pH2, TH2, qxH2, qxH2_total, Sloss, \
    QH2, RxH2, QH2_total, AlbedoH2, WallH2, fSH, SH, SP, SHP, NuE, NuDis, ESH, Eaxis, error = Kinetic_H2(\
        vxM, vrM, xH2, TnormM, mu, TiM, TeM, nM, vxiM, fh2BC, GammaxH2BC, NuLoss, PipeDiaM, fHM, SH2, fH2, nH2, THP, \
        truncate=truncate, Simple_CX=Simple_CX, Max_Gen=max_gen, Compute_H_Source=Compute_H_Source,\
        H2_H2_EL=H2_H2_EL,H2_P_EL=H2_P_EL,H2_H_EL=H2_H_EL,H2_HP_CX=H2_HP_CX, ni_correct=ni_correct,\
        Compute_Errors=H2compute_errors, plot=H2plot,debug=H2debug,debrief=H2debrief,pause=H2pause, g=g) # fixed inputs - GG 2/26

# Kinetic_H2_Ouput common block- GG 2/15
piH2_xx = g.Kinetic_H2_Output_piH2_xx
piH2_yy = g.Kinetic_H2_Output_piH2_yy
piH2_zz = g.Kinetic_H2_Output_piH2_zz
RxH2CX = g.Kinetic_H2_Output_RxH2CX
RxH_H2 = g.Kinetic_H2_Output_RxH_H2
RxP_H2 = g.Kinetic_H2_Output_RxP_H2
RxW_H2 = g.Kinetic_H2_Output_RxW_H2
EH2CX = g.Kinetic_H2_Output_EH2CX
EH_H2 = g.Kinetic_H2_Output_EH_H2
EP_H2 = g.Kinetic_H2_Output_EP_H2
EW_H2 = g.Kinetic_H2_Output_EW_H2
Epara_PerpH2_H2 = g.Kinetic_H2_Output_Epara_PerpH2_H2       

# kinetic_h2_moments common block - GG 2/15
nHM = g.Kinetic_H2_H_moments_nH
VxHM = g.Kinetic_H2_H_moments_VxH
THM = g.Kinetic_H2_H_moments_TH

# Interpolate H2 data onto H mesh: fH2 -> fH2A, fSH -> fSHA, nHP -> nHPA, THP -> THPA
do_warn = 5.0E-3


In [50]:
fH2


array([[[2.94515433e+14, 2.94501205e+14, 2.94481790e+14, 2.94463161e+14,
         2.94449661e+14, 2.94442006e+14],
        [3.61686261e+14, 3.61618434e+14, 3.61526351e+14, 3.61438821e+14,
         3.61376613e+14, 3.61342965e+14],
        [4.62395081e+14, 4.62131262e+14, 4.61777255e+14, 4.61443343e+14,
         4.61208053e+14, 4.61082948e+14],
        [6.29253128e+14, 6.28267600e+14, 6.27081250e+14, 6.26003727e+14,
         6.25251503e+14, 6.24854850e+14],
        [9.57151119e+14, 9.51893000e+14, 9.47798561e+14, 9.44620851e+14,
         9.42450752e+14, 9.41312214e+14],
        [1.87264942e+15, 1.83720645e+15, 1.82086113e+15, 1.81100317e+15,
         1.80446126e+15, 1.80103210e+15],
        [1.63521212e+15, 1.63521212e+15, 1.63521212e+15, 1.63521212e+15,
         1.63521212e+15, 1.63521212e+15],
        [1.63521212e+15, 1.63521212e+15, 1.63521212e+15, 1.63521212e+15,
         1.63521212e+15, 1.63521212e+15],
        [1.63521212e+15, 1.63521212e+15, 1.63521212e+15, 1.63521212e+15,
       

In [38]:
vrM


array([0.50368813, 1.03923433, 1.60663863, 2.205901  , 2.83702146,
       3.5       ])

In [39]:
vxM


array([-3.5       , -2.83702146, -2.205901  , -1.60663863, -1.03923433,
       -0.50368813,  0.50368813,  1.03923433,  1.60663863,  2.205901  ,
        2.83702146,  3.5       ])

In [40]:
xH2


array([0.13734576, 0.13835662, 0.14435662, 0.15035662, 0.15635662])

In [41]:
TnormM


np.float64(12.21783729943014)

In [42]:
vrA

array([0.06271081, 0.13724153, 0.22359217, 0.32176272, 0.43175319,
       0.55356357, 0.68719387, 0.83264408, 0.98991421, 1.15900425,
       1.33991421, 1.53264408, 1.73719387, 1.95356357, 2.18175319,
       2.42176272, 2.67359217, 2.93724153, 3.21271081, 3.5       ])

In [43]:
vxA

array([-3.5       , -3.21271081, -2.93724153, -2.67359217, -2.42176272,
       -2.18175319, -1.95356357, -1.73719387, -1.53264408, -1.33991421,
       -1.15900425, -0.98991421, -0.83264408, -0.68719387, -0.55356357,
       -0.43175319, -0.32176272, -0.22359217, -0.13724153, -0.06271081,
        0.06271081,  0.13724153,  0.22359217,  0.32176272,  0.43175319,
        0.55356357,  0.68719387,  0.83264408,  0.98991421,  1.15900425,
        1.33991421,  1.53264408,  1.73719387,  1.95356357,  2.18175319,
        2.42176272,  2.67359217,  2.93724153,  3.21271081,  3.5       ])

In [44]:
xH


array([0.13734576, 0.1376182 , 0.1380182 , 0.1384182 , 0.1388182 ,
       0.1392182 , 0.1396182 , 0.1400182 , 0.1404182 , 0.1408182 ,
       0.1412182 , 0.1416182 , 0.1420182 , 0.1424182 , 0.1428182 ,
       0.1432182 , 0.1436182 , 0.1440182 , 0.1444182 , 0.1448182 ,
       0.1452182 , 0.1456182 , 0.1460182 , 0.1464182 , 0.1468182 ,
       0.1472182 , 0.1476182 , 0.1480182 , 0.1484182 , 0.1488182 ,
       0.1492182 , 0.1496182 , 0.1500182 , 0.1504182 , 0.1508182 ,
       0.1512182 , 0.1516182 , 0.1520182 , 0.1524182 , 0.1528182 ,
       0.1532182 , 0.1536182 , 0.1540182 , 0.1544182 , 0.1548182 ,
       0.1552182 , 0.1556182 , 0.1560182 , 0.1564182 , 0.1568182 ,
       0.1572182 , 0.1576182 , 0.1580182 , 0.1584182 , 0.1588182 ,
       0.1592182 , 0.1596182 , 0.1600182 , 0.1604182 , 0.1608182 ,
       0.1612182 , 0.1616182 , 0.1620182 , 0.1624182 , 0.1628182 ,
       0.1632182 , 0.1636182 , 0.1640182 , 0.1644182 , 0.1648182 ,
       0.1652182 , 0.1656182 , 0.1660182 , 0.1664182 , 0.16681

In [45]:
TnormA


np.float64(74.3173496215798)

In [46]:
#do_warn=do_warn
do_warn

0.005

In [47]:
#debug=interp_debug
interp_debug

0

In [48]:
#g=g
g

In [49]:
fH2A = np.maximum(interp_fvrvxx(fH2,vrM,vxM,xH2,TnormM,vrA,vxA,xH,TnormA, do_warn=do_warn, debug=interp_debug, g=g),0 )


ValueError: operands could not be broadcast together with shapes (20,) (6,) 

In [51]:
####
## Analizing 
##
interp_fvrvxx(fH2,vrM,vxM,xH2,TnormM,vrA,vxA,xH,\
              TnormA, do_warn=do_warn, debug=interp_debug, g=g)

ValueError: operands could not be broadcast together with shapes (20,) (6,) 

In [52]:
####
## Going inside interp_fvrvxx.py 
##

In [53]:
####
## Variables for interp_fvrvxx.py
## Like a function
#fH2,vrM,vxM,xH2,TnormM,vrA,vxA,xH,\
#              TnormA, do_warn=do_warn, debug=interp_debug, g=g

In [54]:
####
## Variables by definition
##
#def interp_fvrvxx(fa,Vra,Vxa,Xa,Tnorma,Vrb,Vxb,Xb,\
#                  Tnormb,do_warn=None, debug=0, correct=1,g=None): # added global variable argument


In [55]:
fa = copy.copy(fH2)
Vra = copy.copy(vrM)
Vxa = copy.copy(vxM)
Xa = copy.copy(xH2)
Tnorma = copy.copy(TnormM)
Vrb = copy.copy(vrA)
Vxb = copy.copy(vxA)
Xb = copy.copy(xH)
Tnormb = copy.copy(TnormA)
do_warn = copy.copy(do_warn)
debug = copy.copy(interp_debug) 
correct=1 #--> it was by default
g = copy.copy(g)

In [56]:
prompt='INTERP_FVRVXX => '

#   Calls INTERP_FVRVXX_internal1 and INTERP_FVRVXX_internal2 common blocks
vra1=g.INTERP_FVRVXX_internal1_vra1
vxa1=g.INTERP_FVRVXX_internal1_vxa1
Tnorma1=g.INTERP_FVRVXX_internal1_Tnorma1
vrb1=g.INTERP_FVRVXX_internal1_vrb1
vxb1=g.INTERP_FVRVXX_internal1_vxb1
Tnormb1=g.INTERP_FVRVXX_internal1_Tnormb1
weight1=g.INTERP_FVRVXX_internal1_weight1 # fixed capitalization - GG
    
vra2=g.INTERP_FVRVXX_internal2_vra2
vxa2=g.INTERP_FVRVXX_internal2_vxa2
Tnorma2=g.INTERP_FVRVXX_internal2_Tnorma2
vrb2=g.INTERP_FVRVXX_internal2_vrb2
vxb2=g.INTERP_FVRVXX_internal2_vxb2
Tnormb2=g.INTERP_FVRVXX_internal2_Tnormb2
weight2=g.INTERP_FVRVXX_internal2_weight2

In [57]:
nvra=Vra.size
nvxa=Vxa.size
nxa=Xa.size

mu=1

fV=np.sqrt(Tnormb/Tnorma)

#   Compute Vtha, Vtha2, Vthb and Vthb2

Vtha=np.sqrt(2*q*Tnorma/(mu*mH))
Vtha2=Vtha*Vtha # fixed capitalization
Vthb=np.sqrt(2*q*Tnormb/(mu*mH))
Vthb2=Vthb*Vthb # fixed capitalization

if fa[0,0,:].size!=nvra:
    raise Exception('Number of elements in fa(*,0,0) and Vra do not agree!')
if fa[0,:,0].size!=nvxa:
    raise Exception('Number of elements in fa(0,*,0) and Vxa do not agree!')
if fa[:,0,0].size!=nxa:
    raise Exception('Number of elements in fa(0,0,*) and Xa do not agree!')

oki=np.bitwise_and(fV*Vrb<=max(Vra),fV*Vrb>=min(Vra)).nonzero()[0]
if oki.size<1:
    raise Exception('No values of Vrb are within range of Vra')
i0,i1=oki[0],oki[-1]

okj=np.bitwise_and(fV*Vxb<=max(Vxa),fV*Vxb>=min(Vxa)).nonzero()[0]
if okj.size<1:
    raise Exception('No values of Vxb are within range of Vxa')
j0,j1=okj[0],okj[-1]

okk=np.bitwise_and(Xb<=max(Xa), Xb>=min(Xa)).nonzero()[0] # deleted fV terms because they shouldnt be there - GG
if okk.size<1:
    raise Exception('No values of Xb are within range of Xa')
k0,k1=okk[0],okk[-1]

nvrb=Vrb.size
nvxb=Vxb.size
nxb=Xb.size

In [58]:
nvrb

20

In [59]:
nvxb

40

In [60]:
nxb

145

In [61]:
fb=np.zeros((nxb,nvxb,nvrb)) # added parenthesis - GG

make_dvr_dvx_out=Make_dVr_dVx(Vra,Vxa)
Vr2pidVra,VrVr4pidVra,dVxa,vraL,vraR,vxaL,vxaR=make_dvr_dvx_out[:7]
Vra2Vxa2=make_dvr_dvx_out[11]
Vr2pidVrb,VrVr4pidVrb,dVxb,vrbL,vrbR,vxbL,vxbR,Vol,Vth_DVx,Vx_DVx,Vr_DVr,Vrb2Vxb2,jpa,jpb,jna,jnb=Make_dVr_dVx(Vrb,Vxb)

#   Determine if Weight was already computed by checking vra_s,vxa_s,Tnorma_s,vrb_s,vxb_s,Tnormb_s for cases 1 and 2

w1_active=0
w1_match=0

In [62]:
if not vra1 is None:
    w1_active=1
    test=0

    test+=vra1[vra1!=Vra].size
    test+=vxa1[vxa1!=Vxa].size

ValueError: operands could not be broadcast together with shapes (20,) (6,) 

In [63]:
test+=vra1[vra1!=Vra]

ValueError: operands could not be broadcast together with shapes (20,) (6,) 

In [65]:
test+=np.not_equal(vra1, Vra)

ValueError: operands could not be broadcast together with shapes (20,) (6,) 

In [66]:
type(Vra)

numpy.ndarray

In [67]:
type(Vra1)

NameError: name 'Vra1' is not defined

In [68]:
type(test)

int